version: '3.7'
services:
  app:
    image: "kaddemimage:${IMAGE_VERSION}"
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddem
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
