version: '3'

services:
  kaddem-app:
    image: souhailamri/kaddem:1.0.0
    container_name: kaddem-app
    ports:
      - "8089:8089"
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/kaddem
      - SERVER_PORT=8089
      - SPRING_DATASOURCE_URL=jdbc:mysql://kaddem-db:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME= root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - kaddem-db

  kaddem-db:
    image: mysql:5.7
    container_name: kaddem-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: kaddem
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
